from sqlalchemy import text
from db import engine

assessment_data = [
    # -----
    # PLANNING & MONITORING
    # -----
    {
        "assessment_criteria": "DevCo Schedule Performance Index (SPI)",
        "weightage": 0.7,
        "formula": "Earned Value (EV) / Planned Value (PV)",
        "data_points_used": "PM-DP-04,PM-DP-05",
        "calculation_type": "ratio",
        "rating_good": ">1",
        "rating_satisfactory": "0.85-1",
        "rating_needs_improvement": "<0.85",
        "pillar": "Planning & Monitoring",
        "description": "Measures schedule performance vs plan",
        "formula_type": "auto"
    },
    {
        "assessment_criteria": "% milestone achievement in accordance with approved plan",
        "weightage": 0.3,
        "formula": "No. of milestones achieved on time/ No. of planned milestones",
        "data_points_used": "PM-DP-07,PM-DP-08",
        "calculation_type": "percentage",
        "rating_good": ">0.7",
        "rating_satisfactory": "0.5-0.7",
        "rating_needs_improvement": "<0.5",
        "pillar": "Planning & Monitoring",
        "description": "Tracks milestone delivery rate",
        "formula_type": "auto"
    },
    {
        "assessment_criteria": "% of projects with approved change requests in design phase since inception with time impact of more than 1 month",
        "weightage": 0.4,
        "formula": "Number of projects with approved change requests in design phase since inception with time impact of more than 1 month  / Total number of projects in design phase",
        "data_points_used": "PM-DP-015,PM-DP-016",
        "calculation_type": "percentage",
        "rating_good": "<0.3",
        "rating_satisfactory": "0.3-0.7",
        "rating_needs_improvement": ">0.7",
        "pillar": "Planning & Monitoring",
        "description": "Tracks % of design-phase projects with >1-month delay due to approved changes",
        "formula_type": "auto"
    },
    {
        "assessment_criteria": "% of projects with approved change requests in construction phase since inception with time impact of more than 4 months",
        "weightage": 0.4,
        "formula": "Number of projects with approved change requests in construction phase since inception with time impact of more than 4 months / Total number of projects in construction phase",
        "data_points_used": "PM-DP-018,PM-DP-019",
        "calculation_type": "percentage",
        "rating_good": "<0.3",
        "rating_satisfactory": "0.3-0.7",
        "rating_needs_improvement": ">0.7",
        "pillar": "Planning & Monitoring",
        "description": "Tracks % of construction-phase projects with >4-month delay due to approved changes",
        "formula_type": "auto"
    },
    {
        "assessment_criteria": "% of projects with approved schedule extension",
        "weightage": 0.2,
        "formula": "Number of Projects with Approved Schedule Extension/Total Number of Projects",
        "data_points_used": "PM-DP-022,PM-DP-023,PM-DP-024",
        "calculation_type": "percentage",
        "rating_good": "<0.2",
        "rating_satisfactory": "0.2-0.4",
        "rating_needs_improvement": ">0.4",
        "pillar": "Planning & Monitoring",
        "description": "Tracks % of projects granted schedule extensions",
        "formula_type": "auto"
    },
    {
        "assessment_criteria": "% of projects with Forecast completion date beyond the latest approved schedule ",
        "weightage": 0.6,
        "formula": "Number of projects with forecast completion date beyond the latest approved schedule / [No. of projects with schedule extension (design stage) +  No. of projects with schedule extension (construction stage)]",
        "data_points_used": "PM-DP-027",
        "calculation_type": "percentage",
        "rating_good": "<0.2",
        "rating_satisfactory": "0.2-0.4",
        "rating_needs_improvement": ">0.4",
        "pillar": "Planning & Monitoring",
        "description": "Tracks % of projects forecasted to exceed latest approved schedule",
        "formula_type": "auto"
    },
    {
        "assessment_criteria": "Is the Forecast Finish Date at a given data date based on the alignment and buy-in from project teams and other listed stakeholders?",
        "weightage": 0.2,
        "formula": "Satisfactory Score if key project stakeholders (engineering, procurement, construction, client teams) were formally briefed, discussed on the forecast date includ any foreseen risks but no formal sign off doc on the forecast finish date is available ",
        "data_points_used": "PM-DP-028",
        "calculation_type": "custom",
        "rating_good": "yes",
        "rating_satisfactory": "yes, but inadequate",
        "rating_needs_improvement": "no",
        "pillar": "Planning & Monitoring",
        "description": "Checks if forecast date is aligned with key stakeholders",
        "formula_type": "auto"
    },
    {
        "assessment_criteria": "Based on the risks identified and approved change requests, has the DevCo conducted a sensitivity assessment on the forecast completion at a given data date?",
        "weightage": 0.2,
        "formula": "Satisfactory if new activities as per the risks identified and discussions with stakeholders are added in the revised programme but do not have logical relationships and there is no comparison of the critical path analysis before and after date change",
        "data_points_used": "PM-DP-029",
        "calculation_type": "custom",
        "rating_good": "yes",
        "rating_satisfactory": "yes, but inadequate",
        "rating_needs_improvement": "no",
        "pillar": "Planning & Monitoring",
        "description": "Checks if sensitivity assessment on forecast completion was conducted based on risks and changes",
        "formula_type": "auto"
    },
    {
        "assessment_criteria": "Has DevCo allocated risk contingency for the identified risks?",
        "weightage": 0.2,
        "formula": "Satisfactory Score if - Contingency allocated but not aligning with the risk severity as per the heat map",
        "data_points_used": "PM-DP-034",
        "calculation_type": "custom",
        "rating_good": "yes",
        "rating_satisfactory": "yes, but inadequate",
        "rating_needs_improvement": "no",
        "pillar": "Planning & Monitoring",
        "description": "Checks if risk contingency is allocated, regardless of alignment with risk severity",
        "formula_type": "auto"
    },
    {
        "assessment_criteria": "Was there any deferment in the project completion date due to unidentified risks?",
        "weightage": 0.3,
        "formula": "Satisfactory Score if - the deferment was less than 1 month",
        "data_points_used": "PM-DP-035",
        "calculation_type": "custom",
        "rating_good": "no",
        "rating_satisfactory": "yes, but less than 1 month",
        "rating_needs_improvement": "yes",
        "pillar": "Planning & Monitoring",
        "description": "Checks if project deferment occurred due to unidentified risks",
        "formula_type": "auto"
    },
    {
        "assessment_criteria": "Was there any Cost Overrun because of identified risk?",
        "weightage": 0.3,
        "formula": "Satisfactory Score if - the cost overrun was less than 5%",
        "data_points_used": "PM-DP-036",
        "calculation_type": "custom",
        "rating_good": "no",
        "rating_satisfactory": "yes, but less than 5%",
        "rating_needs_improvement": "yes",
        "pillar": "Planning & Monitoring",
        "description": "Checks if cost overrun occurred due to identified risks",
        "formula_type": "auto"
    },
    {
        "assessment_criteria": "Was there any Cost Overrun because of unidentified risk?",
        "weightage": 0.2,
        "formula": "Satisfactory Score if - the cost overrun was less than 1%",
        "data_points_used": "PM-DP-037",
        "calculation_type": "custom",
        "rating_good": "no",
        "rating_satisfactory": "yes, but less than 1%",
        "rating_needs_improvement": "yes",
        "pillar": "Planning & Monitoring",
        "description": "Checks if cost overrun occurred due to unidentified risks",
        "formula_type": "auto"
    },
    {
        "assessment_criteria": "Risk Control Rate of the identified risks at DevCo Level",
        "weightage": 0.4,
        "formula": "Number of Controlled Risks / Total number of identified risks",
        "data_points_used": "PM-DP-047,PM-DP-48",
        "calculation_type": "ratio",
        "rating_good": ">0.7",
        "rating_satisfactory": "0.4-0.7",
        "rating_needs_improvement": "<0.4",
        "pillar": "Planning & Monitoring",
        "description": "Tracks % of identified risks effectively controlled by DevCo",
        "formula_type": "auto"
    },
    {
        "assessment_criteria": "Is the DevCo fully compliant with Risk Management Plan requirements?",
        "weightage": 0.2,
        "formula": "Satisfactory Score if - the risks were identified, mitigations planned but not communicated to all the relevant stakeholders. And the risk register is updated",
        "data_points_used": "PM-DP-050",
        "calculation_type": "custom",
        "rating_good": "yes",
        "rating_satisfactory": "yes, but inadequate",
        "rating_needs_improvement": "no",
        "pillar": "Planning & Monitoring",
        "description": "Checks DevCo's compliance with risk management plan requirements",
        "formula_type": "auto"
    },
    {
        "assessment_criteria": "Is there a difference in the time impact forecast before and after the risk event has triggered?",
        "weightage": 0.2,
        "formula": "Satisfactory Score if - the time impact is less than 2 weeks for Design phase completion and less than 1 month of Construction Phase Completion",
        "data_points_used": "PM-DP-052",
        "calculation_type": "custom",
        "rating_good": "no",
        "rating_satisfactory": "yes, but less than 2 weeks",
        "rating_needs_improvement": "yes",
        "pillar": "Planning & Monitoring",
        "description": "Checks if risk events caused significant change in time impact forecasts",
        "formula_type": "auto"
    },
    {
        "assessment_criteria": "Is there a difference in the Cost impact forecast before and after the risk event has triggered?",
        "weightage": 0.2,
        "formula": "Satisfactory Score if - the cost impact is less than 0.5% of the  identified risk costing",
        "data_points_used": "PM-DP-053",
        "calculation_type": "custom",
        "rating_good": "no",
        "rating_satisfactory": "yes, but less than 0.5%",
        "rating_needs_improvement": "yes",
        "pillar": "Planning & Monitoring",
        "description": "Checks if risk events caused significant change in cost impact forecasts",
        "formula_type": "auto"
    },
    # -----
    # DESIGN & TECHNICAL
    # -----
    {
        "assessment_criteria": "Similarity between Original/Approved and Latest CGI and Animation",
        "weightage": 0.3,
        "formula": "(Percentage similarity between Approved CGI and Latest CGI at same angle and scale) + (Percentage similarity between Approved Animation and Latest Animation at same camera angle) / 2",
        "data_points_used": "DT-DP-001,DT-DP-002",
        "calculation_type": "ratio",
        "rating_good": ">0.7",
        "rating_satisfactory": "0.5-0.7",
        "rating_needs_improvement": "<0.5",
        "pillar": "Design & Technical",
        "description": "Measures visual consistency between approved and latest CGI/animation",
        "formula_type": "auto"
    },
    {
        "assessment_criteria": "Does the Latest Material Palette & Finish Schedule support the look of the Approved CGI?",
        "weightage": 0.2,
        "formula": "Material Palette & Finish Schedule matched Approved CGI",
        "data_points_used": "DT-DP-003",
        "calculation_type": "custom",
        "rating_good": ">0.7",
        "rating_satisfactory": "0.5-0.7",
        "rating_needs_improvement": "<0.5",
        "pillar": "Design & Technical",
        "description": "Checks if latest materials and finishes align with approved CGI",
        "formula_type": "auto"
    },
    {
        "assessment_criteria": "Does the DevCo have Design & Technical Guidelines (including Look & Feel Design Guidelines)?",
        "weightage": 0.2,
        "formula": "The Design and Technical Guidelines exist",
        "data_points_used": "DT-DP-004",
        "calculation_type": "custom",
        "rating_good": "Yes",
        "rating_satisfactory": "",
        "rating_needs_improvement": "No",
        "pillar": "Design & Technical",
        "description": "Checks if DevCo has established design and technical guidelines",
        "formula_type": "auto"
    },
    {
        "assessment_criteria": "Do DevCo projects comply with DDTG?",
        "weightage": 0.3,
        "formula": "Material Palette & Finish Schedule aligns with Look & Feel Guideline ",
        "data_points_used": "DT-DP-005",
        "calculation_type": "custom",
        "rating_good": ">0.7",
        "rating_satisfactory": "0.5-0.7",
        "rating_needs_improvement": "<0.5",
        "pillar": "Design & Technical",
        "description": "Checks if DevCo projects comply with design and technical guidelines (DDTG)",
        "formula_type": "auto"
    },
    {
        "assessment_criteria": "% variance from approved Built-Up Area (BUA)",
        "weightage": 0.3,
        "formula": "(Latest BUA - Approved BUA) / Approved BUA",
        "data_points_used": "DT-DP-010,DT-DP-011",
        "calculation_type": "ratio",
        "rating_good": "<0.15",
        "rating_satisfactory": "0.15-0.30",
        "rating_needs_improvement": ">0.30",
        "pillar": "Design & Technical",
        "description": "Tracks % variance from approved built-up area (BUA)",
        "formula_type": "auto"
    },
    {
        "assessment_criteria": "% variance in land use permit area",
        "weightage": 0.3,
        "formula": "(Latest Land Area - Approved Land Area) / Approved Land Area",
        "data_points_used": "DT-DP-012,DT-DP-013",
        "calculation_type": "ratio",
        "rating_good": "<0.15",
        "rating_satisfactory": "0.15-0.30",
        "rating_needs_improvement": ">0.30",
        "pillar": "Design & Technical",
        "description": "Tracks % variance from approved land use permit area",
        "formula_type": "auto"
    },
    {
        "assessment_criteria": "% variance from approved population",
        "weightage": 0.4,
        "formula": "(Latest Population - Approved Population) / Approved Population",
        "data_points_used": "DT-DP-014,DT-DP-015",
        "calculation_type": "ratio",
        "rating_good": "<0.30",
        "rating_satisfactory": "0.30-0.40",
        "rating_needs_improvement": ">0.40",
        "pillar": "Design & Technical",
        "description": "Tracks % variance from approved population figures",
        "formula_type": "auto"
    },
    {
        "assessment_criteria": "% value of modularization compared to the total construction value",
        "weightage": 0.2,
        "formula": "Modularized Construction Cost / Total Construction Cost",
        "data_points_used": "DT-DP-024,DT-DP-025",
        "calculation_type": "ratio",
        "rating_good": ">0.4",
        "rating_satisfactory": "0.2-0.4",
        "rating_needs_improvement": "<0.2",
        "pillar": "Design & Technical",
        "description": "Tracks % of construction value derived from modularization",
        "formula_type": "auto"
    },
    {
        "assessment_criteria": "Have all projects completed a Constructability Report/Document? ",
        "weightage": 0.2,
        "formula": "Constructability Report exists",
        "data_points_used": "DT-DP-030",
        "calculation_type": "custom",
        "rating_good": "yes",
        "rating_satisfactory": "",
        "rating_needs_improvement": "no",
        "pillar": "Design & Technical",
        "description": "Checks if all projects have completed a constructability report",
        "formula_type": "auto"
    },
    {
        "assessment_criteria": "Was design for Enabling Work Package considerd as part of the design process to ensure the readiness of the site for the main construction work?",
        "weightage": 0.2,
        "formula": "Consideration of design for enabling work package",
        "data_points_used": "DT-DP-035",
        "calculation_type": "custom",
        "rating_good": "yes",
        "rating_satisfactory": "",
        "rating_needs_improvement": "no",
        "pillar": "Design & Technical",
        "description": "Checks if enabling work design was considered to ensure site readiness",
        "formula_type": "auto"
    },
    {
        "assessment_criteria": "Are documentation packages meeting the LOD requirements of the latest Design Stage Gate?",
        "weightage": 0.2,
        "formula": "LOD Documented matches LOD Required",
        "data_points_used": "DT-DP-036,DT-DP-037",
        "calculation_type": "custom",
        "rating_good": "yes",
        "rating_satisfactory": "",
        "rating_needs_improvement": "no",
        "pillar": "Design & Technical",
        "description": "Checks if documentation meets LOD requirements of latest design stage gate",
        "formula_type": "auto"
    },
    {
        "assessment_criteria": "Have all projects adopted digital delivery using BIM and/or GIS?",
        "weightage": 0.2,
        "formula": "BIM Documentation exists",
        "data_points_used": "DT-DP-039",
        "calculation_type": "custom",
        "rating_good": "yes",
        "rating_satisfactory": "",
        "rating_needs_improvement": "no",
        "pillar": "Design & Technical",
        "description": "Checks if projects have adopted digital delivery using BIM and/or GIS",
        "formula_type": "auto"
    },
    {
        "assessment_criteria": "Is project delivery occurring in accordance with the latest approved design strategy?",
        "weightage": 0.1,
        "formula": "Review Latest Approved Design Strategy and compare with the Stage Gate Design Report",
        "data_points_used": "DT-DP-040",
        "calculation_type": "custom",
        "rating_good": "yes",
        "rating_satisfactory": "",
        "rating_needs_improvement": "no",
        "pillar": "Design & Technical",
        "description": "Checks if project delivery aligns with the latest approved design strategy",
        "formula_type": "auto"
    },
    {
        "assessment_criteria": "% of projects with completed technical design/peer reviews and verifications/certifications as required for the latest Design Stage Gate",
        "weightage": 0.2,
        "formula": "Check the Design Review & Verification Register, assess if correct number of Design Reviews have occurred in accordance with the Design Management Report",
        "data_points_used": "DT-DP-041",
        "calculation_type": "custom",
        "rating_good": ">0.7",
        "rating_satisfactory": "0.5-0.7",
        "rating_needs_improvement": "<0.5",
        "pillar": "Design & Technical",
        "description": "Tracks % of projects with completed technical reviews and certifications per latest design stage gate",
        "formula_type": "auto"
    },
    {
        "assessment_criteria": "% of Corrective Actions closed",
        "weightage": 0.1,
        "formula": "Closed Corrective Actions / Total Corrective Actions",
        "data_points_used": "DT-DP-042,DT-DP-043",
        "calculation_type": "ratio",
        "rating_good": ">0.7",
        "rating_satisfactory": "0.4-0.7",
        "rating_needs_improvement": "<0.4",
        "pillar": "Design & Technical",
        "description": "Tracks % of corrective actions successfully closed",
        "formula_type": "auto"
    },
    {
        "assessment_criteria": "Average Cycle time to close corrective actions",
        "weightage": 0.1,
        "formula": "Average number of days between Date Corrective Action is recorded in the Corrective Action Register and the Date Corrective Action is Closed",
        "data_points_used": "DT-DP-044",
        "calculation_type": "custom",
        "rating_good": "<14days",
        "rating_satisfactory": "14-30days",
        "rating_needs_improvement": ">30days",
        "pillar": "Design & Technical",
        "description": "Tracks average time taken to close corrective actions",
        "formula_type": "auto"
    },
    {
        "assessment_criteria": "Is the average cycle time to complete reviews and certifications in accordance with the Design Management Report?",
        "weightage": 0.2,
        "formula": "Average number of days between Design Review Submittals and Completion of the Design Reviews compared to the number of days required to complete the Design Reviews in accordance with the Design Management Report",
        "data_points_used": "DT-DP-045",
        "calculation_type": "custom",
        "rating_good": "yes",
        "rating_satisfactory": "",
        "rating_needs_improvement": "no",
        "pillar": "Design & Technical",
        "description": "Checks if average review and certification cycle time aligns with design management targets",
        "formula_type": "auto"
    },
    {
        "assessment_criteria": "Has the DevCo engaged independent certification of major critical elements?",
        "weightage": 0.3,
        "formula": "Independent Certification exists",
        "data_points_used": "DT-DP-046",
        "calculation_type": "custom",
        "rating_good": "yes",
        "rating_satisfactory": "",
        "rating_needs_improvement": "no",
        "pillar": "Design & Technical",
        "description": "Checks if independent certification has been obtained for major critical elements",
        "formula_type": "auto"
    },
    {
        "assessment_criteria": "Are all project designs integrated with Regional Infrastructure & Mobility Plans?",
        "weightage": 0.5,
        "formula": "The Infrastructure and Engineering Report references the Regional Infrastructure & Mobility Plans and demonstrates adoption of Regional Strategies",
        "data_points_used": "DT-DP-047",
        "calculation_type": "custom",
        "rating_good": "yes",
        "rating_satisfactory": "",
        "rating_needs_improvement": "no",
        "pillar": "Design & Technical",
        "description": "Checks if project designs are aligned with regional infrastructure and mobility plans",
        "formula_type": "auto"
    },
    {
        "assessment_criteria": "Do all projects comply with environmental guidelines in accordance with ESIA?",
        "weightage": 0.5,
        "formula": "Key Environmental Risks and Site Environmental Factors are covered in the Environmental Compliance Report",
        "data_points_used": "DT-DP-050",
        "calculation_type": "custom",
        "rating_good": "yes",
        "rating_satisfactory": "",
        "rating_needs_improvement": "no",
        "pillar": "Design & Technical",
        "description": "Checks if all projects comply with environmental guidelines per ESIA requirements",
        "formula_type": "auto"
    },
    {
        "assessment_criteria": "% of projects with Code Compliance Violations",
        "weightage": 0.2,
        "formula": "Total Number of Code Compliance Violations taken from the Code Compliance Assessment Report",
        "data_points_used": "DT-DP-051",
        "calculation_type": "count",
        "rating_good": "<0.1",
        "rating_satisfactory": "0.1-0.3",
        "rating_needs_improvement": ">0.3",
        "pillar": "Design & Technical",
        "description": "Tracks % of projects with code compliance violations",
        "formula_type": "auto"
    },
    {
        "assessment_criteria": "% of approved deviation waivers against compliant codes & standards",
        "weightage": 0.2,
        "formula": "Total Waivers Approved / Total Waiver Applications Submitted",
        "data_points_used": "DT-DP-052,DT-DP-053",
        "calculation_type": "ratio",
        "rating_good": ">0.7",
        "rating_satisfactory": "0.5-0.7",
        "rating_needs_improvement": "<0.5",
        "pillar": "Design & Technical",
        "description": "Tracks % of approved waivers against codes and standards",
        "formula_type": "auto"
    },
    {
        "assessment_criteria": "Have all required Stakeholder Submittals been issued?",
        "weightage": 0.15,
        "formula": "Stakeholder Submittal Dates are in accordance with the Stakeholder Management Plan to ensure approvals can be achieved in line with Stage Gate completion requirements",
        "data_points_used": "DT-DP-054",
        "calculation_type": "custom",
        "rating_good": "yes",
        "rating_satisfactory": "",
        "rating_needs_improvement": "no",
        "pillar": "Design & Technical",
        "description": "Checks if all required stakeholder submittals have been issued on time",
        "formula_type": "auto"
    },
    {
        "assessment_criteria": "% of time critical Stakeholder Approvals Pending impacting Design Stage Gate completion",
        "weightage": 0.15,
        "formula": "Number of Stakeholder approvals pending / Total number of stakeholder approvals required",
        "data_points_used": "DT-DP-055,DT-DP-056",
        "calculation_type": "ratio",
        "rating_good": "<0.2",
        "rating_satisfactory": "0.2-0.3",
        "rating_needs_improvement": ">0.3",
        "pillar": "Design & Technical",
        "description": "Tracks % of pending stakeholder approvals impacting design stage gate completion",
        "formula_type": "auto"
    },
    {
        "assessment_criteria": "Does the Stakeholder Engagement Plan include proactive communication process to ensure timely coordination and approvals?",
        "weightage": 0.15,
        "formula": "Proactive communication in Stakeholder Engagement Plan",
        "data_points_used": "DT-DP-057",
        "calculation_type": "custom",
        "rating_good": "yes",
        "rating_satisfactory": "",
        "rating_needs_improvement": "no",
        "pillar": "Design & Technical",
        "description": "Checks if stakeholder engagement plan includes proactive communication for timely approvals",
        "formula_type": "auto"
    },
    {
        "assessment_criteria": "% of Stakeholder Comments Closed",
        "weightage": 0.15,
        "formula": "Stakeholder Comments Closed / Total Stakeholder Comments",
        "data_points_used": "DT-DP-058,DT-DP-059",
        "calculation_type": "ratio",
        "rating_good": ">0.7",
        "rating_satisfactory": "0.5-0.7",
        "rating_needs_improvement": "<0.5",
        "pillar": "Design & Technical",
        "description": "Tracks % of stakeholder comments successfully closed",
        "formula_type": "auto"
    },
    {
        "assessment_criteria": "% of projects achieving DevCo ESG Targets",
        "weightage": 1,
        "formula": "Actual ESG Target / Planned ESG Target",
        "data_points_used": "DT-DP-061,DT-DP-062",
        "calculation_type": "ratio",
        "rating_good": ">0.7",
        "rating_satisfactory": "0.5-0.7",
        "rating_needs_improvement": "<0.5",
        "pillar": "Design & Technical",
        "description": "Tracks % of projects meeting DevCo ESG targets",
        "formula_type": "auto"
    },
    {
        "assessment_criteria": "Does the DevCo ESG Target align with globally recognized Best Practice Targets?",
        "weightage": 1,
        "formula": "Alignment with globally recognized Best Practice Targets",
        "data_points_used": "DT-DP-063",
        "calculation_type": "custom",
        "rating_good": "yes",
        "rating_satisfactory": "",
        "rating_needs_improvement": "no",
        "pillar": "Design & Technical",
        "description": "Checks if DevCo ESG targets align with global best practice standards",
        "formula_type": "auto"
    },
    # -----
    # Development & Construction
    # -----
    {
        "assessment_criteria": "% of CESMP mitigation measures which align with ESIA*",
        "weightage": 0.1,
        "formula": "Environmental mitigation measures included in CESMP / Environmental mitigation measures recommended in ESIA",
        "data_points_used": "DC-DP-001,DC-DP-002",
        "calculation_type": "ratio",
        "rating_good": ">0.8",
        "rating_satisfactory": "0.6-0.8",
        "rating_needs_improvement": "<0.6",
        "pillar": "Development & Construction",
        "description": "Tracks % of CESMP mitigation measures aligned with ESIA recommendations",
        "formula_type": "auto"
    },
    {
        "assessment_criteria": "Has the Construction Execution Plan been updated to reflect the latest stage of construction?",
        "weightage": 0.15,
        "formula": "Update of construction execution plan",
        "data_points_used": "DC-DP-003",
        "calculation_type": "custom",
        "rating_good": "yes",
        "rating_satisfactory": "",
        "rating_needs_improvement": "no",
        "pillar": "Development & Construction",
        "description": "Checks if the construction execution plan is updated to reflect the latest construction stage",
        "formula_type": "auto"
    },
    {
        "assessment_criteria": "Has the construction sequence and method statement been reviewed and approved?",
        "weightage": 0.15,
        "formula": "Review and approval of construction sequence and method statement",
        "data_points_used": "DC-DP-005",
        "calculation_type": "custom",
        "rating_good": "yes",
        "rating_satisfactory": "",
        "rating_needs_improvement": "no",
        "pillar": "Development & Construction",
        "description": "Checks if construction sequence and method statement have been reviewed and approved",
        "formula_type": "auto"
    },
    {
        "assessment_criteria": "Is total land acquisition sufficient to achieve the area required for construction site logistics?",
        "weightage": 0.1,
        "formula": "Sufficient land acquired",
        "data_points_used": "DC-DP-006,DC-DP-007",
        "calculation_type": "custom",
        "rating_good": "yes",
        "rating_satisfactory": "",
        "rating_needs_improvement": "no",
        "pillar": "Development & Construction",
        "description": "Checks if land acquired is sufficient for construction site logistics",
        "formula_type": "auto"
    },
    {
        "assessment_criteria": "Have Traffic Simulations been completed in preparing the Site & Logistics Plan?",
        "weightage": 0.1,
        "formula": "Completion of traffic simulations",
        "data_points_used": "DC-DP-010",
        "calculation_type": "custom",
        "rating_good": "yes",
        "rating_satisfactory": "",
        "rating_needs_improvement": "no",
        "pillar": "Development & Construction",
        "description": "Checks if traffic simulations have been completed for the site and logistics plan",
        "formula_type": "auto"
    },
    {
        "assessment_criteria": "Has the Project Execution Plan been updated and approved in the last 12 months?",
        "weightage": 0.1,
        "formula": "Date of latest approved Project Execution Plan less than 12 months from Current Date",
        "data_points_used": "DC-DP-011",
        "calculation_type": "custom",
        "rating_good": "yes",
        "rating_satisfactory": "",
        "rating_needs_improvement": "no",
        "pillar": "Development & Construction",
        "description": "Checks if the project execution plan has been updated and approved within the last 12 months",
        "formula_type": "auto"
    },
    {
        "assessment_criteria": "% of Stakeholder MOU** / LUPs*** not executed in accordance with critical lead time",
        "weightage": 0.3,
        "formula": "Number of Stakeholder MOU or Land Use Permits not executed on time/ Total number of Stakeholder MOU or Land Use Permits required",
        "data_points_used": "DC-DP-015,DC-DP-016",
        "calculation_type": "ratio",
        "rating_good": "<0.2",
        "rating_satisfactory": "0.2-0.6",
        "rating_needs_improvement": ">0.6",
        "pillar": "Development & Construction",
        "description": "Tracks % of stakeholder MOUs or land use permits delayed beyond critical lead times",
        "formula_type": "auto"
    },
    {
        "assessment_criteria": "% of Workforce Hired against Workforce Estimates",
        "weightage": 0.3,
        "formula": "Actual workforce employed / forecast workforce requirements",
        "data_points_used": "DC-DP-024,DC-DP-025",
        "calculation_type": "ratio",
        "rating_good": ">0.9",
        "rating_satisfactory": "0.7-0.9",
        "rating_needs_improvement": "<0.7",
        "pillar": "Development & Construction",
        "description": "Tracks % of workforce hired against forecast workforce estimates",
        "formula_type": "auto"
    },
    {
        "assessment_criteria": "% of Labor Camp Capacity against Workforce Estimates",
        "weightage": 0.3,
        "formula": "Actual number of labor camps / Forecast number of labor camps",
        "data_points_used": "DC-DP-028,DC-DP-029",
        "calculation_type": "ratio",
        "rating_good": ">0.9",
        "rating_satisfactory": "0.7-0.9",
        "rating_needs_improvement": "<0.7",
        "pillar": "Development & Construction",
        "description": "Tracks % of labor camp capacity against forecast workforce requirements",
        "formula_type": "auto"
    },
    {
        "assessment_criteria": "% of Material Supply Capacity against Material Demand Estimates",
        "weightage": 0.4,
        "formula": "Actual number of batching plants / forecast number of batching plants",
        "data_points_used": "DC-DP-030,DC-DP-031",
        "calculation_type": "ratio",
        "rating_good": ">0.8",
        "rating_satisfactory": "0.4-0.8",
        "rating_needs_improvement": "<0.4",
        "pillar": "Development & Construction",
        "description": "Tracks % of material supply capacity against forecast material demand",
        "formula_type": "auto"
    },
    {
        "assessment_criteria": "Did DevCo adhere to Technical Submittals Review Cycle Time (RCT)?",
        "weightage": 0.1,
        "formula": "Adherence to Technical Submittals Review Cycle Time",
        "data_points_used": "DC-DP-036,DC-DP-037",
        "calculation_type": "custom",
        "rating_good": "yes",
        "rating_satisfactory": "",
        "rating_needs_improvement": "no",
        "pillar": "Development & Construction",
        "description": "Checks if DevCo adhered to technical submittals review cycle time (RCT)",
        "formula_type": "auto"
    },
    {
        "assessment_criteria": "% of approved shop drawing reviews vs planned",
        "weightage": 0.15,
        "formula": "Total number of shop drawing reviews approved / Total number of shop drawing review requests",
        "data_points_used": "DC-DP-040,DC-DP-041",
        "calculation_type": "ratio",
        "rating_good": ">0.9",
        "rating_satisfactory": "0.6-0.9",
        "rating_needs_improvement": "<0.6",
        "pillar": "Development & Construction",
        "description": "Tracks % of approved shop drawing reviews vs planned",
        "formula_type": "auto"
    },
    {
        "assessment_criteria": "% of approved product waivers vs product specified",
        "weightage": 0.15,
        "formula": "Total number of product sample & materials approved / Total number of product sample & material approvals requested",
        "data_points_used": "DC-DP-044,DC-DP-045",
        "calculation_type": "ratio",
        "rating_good": ">0.9",
        "rating_satisfactory": "0.6-0.9",
        "rating_needs_improvement": "<0.6",
        "pillar": "Development & Construction",
        "description": "Tracks % of approved product waivers vs specified products",
        "formula_type": "auto"
    },
    {
        "assessment_criteria": "% of Certified As-Built Drawing Packages vs Planned",
        "weightage": 0.2,
        "formula": "Number of As-built reviews / approvals / Number of As-Built review requests",
        "data_points_used": "DC-DP-049,DC-DP-050",
        "calculation_type": "ratio",
        "rating_good": ">0.8",
        "rating_satisfactory": "0.6-0.8",
        "rating_needs_improvement": "<0.6",
        "pillar": "Development & Construction",
        "description": "Tracks % of certified as-built drawing packages vs planned",
        "formula_type": "auto"
    },
    {
        "assessment_criteria": "MIR Inspection Rate",
        "weightage": 0.1,
        "formula": "Number of MIR Inspected / Total number of MIRs requested",
        "data_points_used": "DC-DP-054,DC-DP-055",
        "calculation_type": "ratio",
        "rating_good": ">0.8",
        "rating_satisfactory": "0.6-0.8",
        "rating_needs_improvement": "<0.6",
        "pillar": "Development & Construction",
        "description": "Tracks % of material inspection requests (MIR) completed",
        "formula_type": "auto"
    },
    {
        "assessment_criteria": "MIR Acceptance and Approval Rate",
        "weightage": 0.1,
        "formula": "Number of Approved MIR / Total number of MIRs requested",
        "data_points_used": "DC-DP-056",
        "calculation_type": "ratio",
        "rating_good": ">0.8",
        "rating_satisfactory": "0.6-0.8",
        "rating_needs_improvement": "<0.6",
        "pillar": "Development & Construction",
        "description": "Tracks % of material inspection requests (MIR) approved",
        "formula_type": "auto"
    },
    {
        "assessment_criteria": "WIR Inspection Rate",
        "weightage": 0.1,
        "formula": "Number of WIR Inspected / Total number of WIRs requested",
        "data_points_used": "DC-DP-058,DC-DP-059",
        "calculation_type": "ratio",
        "rating_good": ">0.8",
        "rating_satisfactory": "0.6-0.8",
        "rating_needs_improvement": "<0.6",
        "pillar": "Development & Construction",
        "description": "Tracks % of work inspection requests (WIR) completed",
        "formula_type": "auto"
    },
    {
        "assessment_criteria": "WIR Acceptance and Approval Rate",
        "weightage": 0.1,
        "formula": "Number of Approved WIR / Total number of WIRs requested",
        "data_points_used": "DC-DP-060",
        "calculation_type": "ratio",
        "rating_good": ">0.8",
        "rating_satisfactory": "0.6-0.8",
        "rating_needs_improvement": "<0.6",
        "pillar": "Development & Construction",
        "description": "Tracks % of work inspection requests (WIR) approved",
        "formula_type": "auto"
    },
    {
        "assessment_criteria": "Does the frequency of Audits align with the QMP? ",
        "weightage": 0.4,
        "formula": "Alignment of audit frequency",
        "data_points_used": "DC-DP-066",
        "calculation_type": "custom",
        "rating_good": "yes",
        "rating_satisfactory": "",
        "rating_needs_improvement": "no",
        "pillar": "Development & Construction",
        "description": "Checks if audit frequency aligns with the Quality Management Plan (QMP)",
        "formula_type": "auto"
    },
    {
        "assessment_criteria": "% closure of Non-Conformance Reports (NCR)",
        "weightage": 0.4,
        "formula": "Number of Non-Conformance Reports Closed / Total Number of Non-Conformance Reports",
        "data_points_used": "DC-DP-067,DC-DP-068",
        "calculation_type": "ratio",
        "rating_good": ">0.8",
        "rating_satisfactory": "0.6-0.8",
        "rating_needs_improvement": "<0.6",
        "pillar": "Development & Construction",
        "description": "Tracks % of non-conformance reports (NCR) successfully closed",
        "formula_type": "auto"
    },
    {
        "assessment_criteria": "Average NCRs closeout Cycle Time",
        "weightage": 0.2,
        "formula": "Sum (NCR Closeout cycle time)/Total number of Non-Conformance Reports",
        "data_points_used": "DC-DP-069",
        "calculation_type": "ratio",
        "rating_good": "<10 days",
        "rating_satisfactory": "10-21 days",
        "rating_needs_improvement": ">21 days",
        "pillar": "Development & Construction",
        "description": "Tracks average time taken to close non-conformance reports (NCRs)",
        "formula_type": "auto"
    },
    {
        "assessment_criteria": "% of procurement packages delivered within the planned lead times defined in the PMP",
        "weightage": 0.2,
        "formula": "Number of Procurement Packages Delivered on Time / Number of Planned Procurement Packages",
        "data_points_used": "DC-DP-086,DC-DP-087",
        "calculation_type": "ratio",
        "rating_good": ">0.8",
        "rating_satisfactory": "0.7-0.8",
        "rating_needs_improvement": "0.4-0.7",
        "pillar": "Development & Construction",
        "description": "Tracks % of procurement packages delivered within planned lead times",
        "formula_type": "auto"
    },
    {
        "assessment_criteria": "% of claims and variations processed within contractual conditions & timeframes and with alignment of internal procedures",
        "weightage": 0.2,
        "formula": "Total number of claims and variations processed within contractual conditions & timeframes and with alignment of internal procedures / Total number of claims and variations",
        "data_points_used": "DC-DP-105,DC-DP-106",
        "calculation_type": "ratio",
        "rating_good": ">0.7",
        "rating_satisfactory": "0.5-0.7",
        "rating_needs_improvement": "<0.5",
        "pillar": "Development & Construction",
        "description": "Tracks % of claims and variations processed on time and in line with procedures",
        "formula_type": "auto"
    },
    {
        "assessment_criteria": "% of packages procured with 100% complete, compliant and well-structured documentation",
        "weightage": 0.2,
        "formula": "Total number of packages procured with 100% complete, compliant and well-structured documentation / Total number of packages",
        "data_points_used": "DC-DP-107,DC-DP-108",
        "calculation_type": "ratio",
        "rating_good": ">0.7",
        "rating_satisfactory": "0.5-0.7",
        "rating_needs_improvement": "<0.5",
        "pillar": "Development & Construction",
        "description": "Tracks % of procurement packages with complete, compliant, and well-structured documentation",
        "formula_type": "auto"
    },
    {
        "assessment_criteria": "% of awarded contracts where vendors appointed passed full due diligence checks",
        "weightage": 0.2,
        "formula": "No. of awarded contracts where vendors appointed passed full due-diligence checks  / Total number of awarded contracts",
        "data_points_used": "DC-DP-109,DC-DP-110",
        "calculation_type": "ratio",
        "rating_good": ">0.9",
        "rating_satisfactory": "0.9.0.85",
        "rating_needs_improvement": "<0.85",
        "pillar": "Development & Construction",
        "description": "Tracks % of awarded contracts with vendors passing full due diligence checks",
        "formula_type": "auto"
    },
    {
        "assessment_criteria": "Did the DevCo complete a Supply Chain Risk-Market Intelligence Assessment in the last quarter?",
        "weightage": 0.2,
        "formula": "Completion of supply chain risk-market intelligence assessment",
        "data_points_used": "DC-DP-113",
        "calculation_type": "custom",
        "rating_good": "yes",
        "rating_satisfactory": "",
        "rating_needs_improvement": "no",
        "pillar": "Development & Construction",
        "description": "Checks if DevCo completed a supply chain risk and market intelligence assessment in the last quarter",
        "formula_type": "auto"
    },
    {
        "assessment_criteria": "% of procurement activities executed as planned in the Annual Procurement Plan",
        "weightage": 0.3,
        "formula": "Number of procurement activities executed as planned / Total number of procurement activities",
        "data_points_used": "DC-DP-114,DC-DP-115",
        "calculation_type": "ratio",
        "rating_good": ">0.6",
        "rating_satisfactory": "0.2-0.6",
        "rating_needs_improvement": "<0.2",
        "pillar": "Development & Construction",
        "description": "Tracks % of procurement activities executed as planned in the annual procurement plan",
        "formula_type": "auto"
    },
    {
        "assessment_criteria": "% of deviations in total awarded contract value with tender cost estimates",
        "weightage": 0.3,
        "formula": "(Value of Contract Awarded - Tender Cost Estimate) / Value of Award Contract",
        "data_points_used": "DC-DP-118,DC-DP-119",
        "calculation_type": "ratio",
        "rating_good": "<0.2",
        "rating_satisfactory": "0.2-0.6",
        "rating_needs_improvement": ">0.6",
        "pillar": "Development & Construction",
        "description": "Tracks % deviation between awarded contract values and tender cost estimates",
        "formula_type": "auto"
    },
    {
        "assessment_criteria": "% of contracts with filed claims",
        "weightage": 0.2,
        "formula": "Number of contracts with filed claims / Total number of awarded contracts",
        "data_points_used": "DC-DP-130",
        "calculation_type": "ratio",
        "rating_good": "<0.2",
        "rating_satisfactory": "0.2-0.6",
        "rating_needs_improvement": ">0.6",
        "pillar": "Development & Construction",
        "description": "Tracks % of contracts with filed claims",
        "formula_type": "auto"
    },
    {
        "assessment_criteria": "Are Payment Certificates and payments being processed in accordance with the Contract terms and conditions?",
        "weightage": 0.1,
        "formula": "Processing of payment certificates and payments",
        "data_points_used": "DC-DP-136",
        "calculation_type": "custom",
        "rating_good": "yes",
        "rating_satisfactory": "",
        "rating_needs_improvement": "no",
        "pillar": "Development & Construction",
        "description": "Checks if payment certificates and payments are processed per contract terms",
        "formula_type": "auto"
    },
    {
        "assessment_criteria": "Are Vendor performance assessment occurring which capture  financial instability, delays, repeated quality issues in real-time?",
        "weightage": 0.1,
        "formula": "Vendor performance assessment",
        "data_points_used": "DC-DP-144",
        "calculation_type": "custom",
        "rating_good": "yes",
        "rating_satisfactory": "",
        "rating_needs_improvement": "no",
        "pillar": "Development & Construction",
        "description": "Checks if vendor performance assessments capture financial, delay, and quality risks in real-time",
        "formula_type": "auto"
    },
    {
        "assessment_criteria": "Does the HSE Management Manual have adequate provision for identification and escalation of high risk activities?",
        "weightage": 0.05,
        "formula": "Provision for identification and escalation of high risk activities",
        "data_points_used": "DC-DP-148",
        "calculation_type": "custom",
        "rating_good": "yes",
        "rating_satisfactory": "",
        "rating_needs_improvement": "no",
        "pillar": "Development & Construction",
        "description": "Checks if HSE manual includes provisions for identifying and escalating high-risk activities",
        "formula_type": "auto"
    },
    {
        "assessment_criteria": "Is the rate of review of the Safety Risk Register in accordance with the HSE Management Manual?",
        "weightage": 0.02,
        "formula": "Review rate of safety risk register",
        "data_points_used": "DC-DP-149",
        "calculation_type": "custom",
        "rating_good": "yes",
        "rating_satisfactory": "",
        "rating_needs_improvement": "no",
        "pillar": "Development & Construction",
        "description": "Checks if safety risk register reviews align with HSE management manual requirements",
        "formula_type": "auto"
    },
    {
        "assessment_criteria": "% of closed Safety Risk items",
        "weightage": 0.04,
        "formula": "Total number of closed Safety Risk items / Total number of safety risk items",
        "data_points_used": "DC-DP-150,DC-DP-151",
        "calculation_type": "ratio",
        "rating_good": ">0.8",
        "rating_satisfactory": "0.6-0.8",
        "rating_needs_improvement": "<0.6",
        "pillar": "Development & Construction",
        "description": "Tracks % of closed safety risk items",
        "formula_type": "auto"
    },
    {
        "assessment_criteria": "Average cycle time to close Safety Risk items",
        "weightage": 0.04,
        "formula": "To input final number. Sum (Cycle time to close safety risk items) / Total number of closed safety risk items",
        "data_points_used": "DC-DP-152",
        "calculation_type": "ratio",
        "rating_good": "<7 days",
        "rating_satisfactory": "7-14 days",
        "rating_needs_improvement": ">14 days",
        "pillar": "Development & Construction",
        "description": "Tracks average time taken to close safety risk items",
        "formula_type": "auto"
    },
    {
        "assessment_criteria": "Average cycle time to close Safety Incident",
        "weightage": 0.05,
        "formula": "To input final number. Sum (Cycle time to close safety incident) / Total number of closed safety incidents",
        "data_points_used": "DC-DP-153",
        "calculation_type": "ratio",
        "rating_good": "<7 days",
        "rating_satisfactory": "7-14 days",
        "rating_needs_improvement": ">14 days",
        "pillar": "Development & Construction",
        "description": "Tracks average time taken to close safety incidents",
        "formula_type": "auto"
    },
    {
        "assessment_criteria": "Is the emergency drill rate compliant with EEPP?",
        "weightage": 0.05,
        "formula": "Compliance of emergency drill rate",
        "data_points_used": "DC-DP-157,DC-DP-158,DC-DP-159,DC-DP-160",
        "calculation_type": "custom",
        "rating_good": "yes",
        "rating_satisfactory": "",
        "rating_needs_improvement": "no",
        "pillar": "Development & Construction",
        "description": "Checks if emergency drill frequency complies with EEPP requirements",
        "formula_type": "auto"
    },
    {
        "assessment_criteria": "Fatality Rate (FR)",
        "weightage": 0.15,
        "formula": "No. of incidents resulting in fatality or severe impairment per 200,000 work hours",
        "data_points_used": "DC-DP-171",
        "calculation_type": "count",
        "rating_good": "0",
        "rating_satisfactory": "0.001-0.0199",
        "rating_needs_improvement": ">0.02",
        "pillar": "Development & Construction",
        "description": "Tracks fatality rate per 200,000 work hours",
        "formula_type": "auto"
    },
    {
        "assessment_criteria": "Lost Time Injury Frequency Rate (LTIFR)",
        "weightage": 0.1,
        "formula": "No. of incidents resulting in lost time per 200,000 work hours",
        "data_points_used": "DC-DP-172",
        "calculation_type": "count",
        "rating_good": "<0.1",
        "rating_satisfactory": "0.1-1.5",
        "rating_needs_improvement": ">1.5",
        "pillar": "Development & Construction",
        "description": "Tracks lost time injury frequency rate per 200,000 work hours",
        "formula_type": "auto"
    },
    {
        "assessment_criteria": "Total Recordable Incident Rate (TRIR)",
        "weightage": 0.1,
        "formula": "No. of recordable incidents per 200,000 work hours",
        "data_points_used": "DC-DP-173",
        "calculation_type": "count",
        "rating_good": "<0.5",
        "rating_satisfactory": "0.5-5",
        "rating_needs_improvement": ">5",
        "pillar": "Development & Construction",
        "description": "Tracks total recordable incident rate per 200,000 work hours",
        "formula_type": "auto"
    },
    {
        "assessment_criteria": "Near Miss Rate",
        "weightage": 0.15,
        "formula": "No. of near misses recorded per 200,000 work hours",
        "data_points_used": "DC-DP-174",
        "calculation_type": "count",
        "rating_good": ">30",
        "rating_satisfactory": "0.1-30",
        "rating_needs_improvement": "0%",
        "pillar": "Development & Construction",
        "description": "Tracks near miss rate per 200,000 work hours",
        "formula_type": "auto"
    },
    {
        "assessment_criteria": "Safety Observation Rate",
        "weightage": 0.1,
        "formula": "No. of safety observation recorded per 200,000 work hours",
        "data_points_used": "DC-DP-175",
        "calculation_type": "count",
        "rating_good": ">200",
        "rating_satisfactory": "10-200",
        "rating_needs_improvement": "<10",
        "pillar": "Development & Construction",
        "description": "Tracks safety observation rate per 200,000 work hours",
        "formula_type": "auto"
    },
    {
        "assessment_criteria": "Leadership Safety Walk Rate",
        "weightage": 0.15,
        "formula": "Total number of Safety Walks with Leadership / Total number of Safety Walks",
        "data_points_used": "DC-DP-179,DC-DP-180",
        "calculation_type": "ratio",
        "rating_good": ">70%",
        "rating_satisfactory": "50-70%",
        "rating_needs_improvement": "<50%",
        "pillar": "Development & Construction",
        "description": "Tracks % of safety walks conducted with leadership involvement",
        "formula_type": "auto"
    },
    {
        "assessment_criteria": "% of Grievances Closed",
        "weightage": 0.15,
        "formula": "Number of grievances closed / Total number of grievances",
        "data_points_used": "DC-DP-184,DC-DP-185",
        "calculation_type": "ratio",
        "rating_good": ">80%",
        "rating_satisfactory": "60-80%",
        "rating_needs_improvement": "<60%",
        "pillar": "Development & Construction",
        "description": "Measures the resolution rate of reported grievances",
        "formula_type": "auto"
    },
    {
        "assessment_criteria": "Average Cycle Time to Close Grievances",
        "weightage": 0.1,
        "formula": "Sum (Cycle time to close grievances) / Total number of grievances",
        "data_points_used": "DC-DP-186",
        "calculation_type": "ratio",
        "rating_good": "<14 days",
        "rating_satisfactory": "14-28 days",
        "rating_needs_improvement": ">28 days",
        "pillar": "Development & Construction",
        "description": "Tracks the average time taken to resolve grievances",
        "formula_type": "auto"
    },
    {
        "assessment_criteria": "% of Welfare Staff vs Total workforce",
        "weightage": 0.2,
        "formula": "Number of Welfare Staff / Total Number of Staff",
        "data_points_used": "DC-DP-189",
        "calculation_type": "ratio",
        "rating_good": ">2%",
        "rating_satisfactory": "1-2%",
        "rating_needs_improvement": "<1%",
        "pillar": "Development & Construction",
        "description": "Measures the proportion of welfare staff within the total workforce",
        "formula_type": "auto"
    },
    {
        "assessment_criteria": "% closed welfare observations or red flag if 0 observations",
        "weightage": 0.1,
        "formula": "Number of Welfare Observations Closed / Total number of Welfare Observations",
        "data_points_used": "DC-DP-192,DC-DP-193",
        "calculation_type": "ratio",
        "rating_good": ">60%",
        "rating_satisfactory": "40-60%",
        "rating_needs_improvement": "<40% ; no observations recorded",
        "pillar": "Development & Construction",
        "description": "Measures the closure rate of welfare-related observations, with attention to unreported cases",
        "formula_type": "auto"
    },
    {
        "assessment_criteria": "% of Welfare Non-compliances closed",
        "weightage": 0.1,
        "formula": "Total Closed Welfare Non-compliances / Total Welfare Non-compliances",
        "data_points_used": "DC-DP-194,DC-DP-195",
        "calculation_type": "ratio",
        "rating_good": ">80%",
        "rating_satisfactory": "60-80%",
        "rating_needs_improvement": "<60%",
        "pillar": "Development & Construction",
        "description": "Measures the closure rate of welfare-related non-compliances",
        "formula_type": "auto"
    },
    {
        "assessment_criteria": "Average Cycle Time to Close Welfare Non-compliances",
        "weightage": 0.1,
        "formula": "Sum (Cycle time to close Welfare Non-compliances) / Total number of Welfare Non-compliances",
        "data_points_used": "DC-DP-196",
        "calculation_type": "ratio",
        "rating_good": "<14 days",
        "rating_satisfactory": "14-28 days",
        "rating_needs_improvement": ">28 days",
        "pillar": "Development & Construction",
        "description": "Tracks the average time taken to close welfare-related non-compliances",
        "formula_type": "auto"
    },
    {
        "assessment_criteria": "Is frequency of Labor Accommodation Inspection occurring in accordance with VMMP?",
        "weightage": 0.25,
        "formula": "Labor accommodation inspection frequency",
        "data_points_used": "DC-DP-204",
        "calculation_type": "custom",
        "rating_good": "yes",
        "rating_satisfactory": "",
        "rating_needs_improvement": "no",
        "pillar": "Development & Construction",
        "description": "Checks whether labor accommodation inspections are conducted as per the VMMP schedule",
        "formula_type": "auto"
    },
    # -----
    # Cost Estimation & Optimization
    # -----
    {
        "assessment_criteria": "Budget Variance",
        "weightage": 0.8,
        "formula": "[Forecast Budget - PIF Approved Capex budget (Initial Business Plan)]/ PIF Approved Capex budget (Initial Business Plan)",
        "data_points_used": "CEO-DP-001,CEO-DP-002",
        "calculation_type": "ratio",
        "rating_good": "<10%",
        "rating_satisfactory": "10-20%",
        "rating_needs_improvement": ">20%",
        "pillar": "Cost Estimation & Optimization",
        "description": "Measures variance between forecasted and approved capital expenditure budgets",
        "formula_type": "auto"
    },
    {
        "assessment_criteria": "% of projects having Budget Variance",
        "weightage": 0.2,
        "formula": "Number of Projects with Budget Variance / Total number of Projects",
        "data_points_used": "CEO-DP-003,CEO-DP-004",
        "calculation_type": "ratio",
        "rating_good": "<10%",
        "rating_satisfactory": "10-30%",
        "rating_needs_improvement": ">30%",
        "pillar": "Cost Estimation & Optimization",
        "description": "Measures the proportion of projects with budget deviations",
        "formula_type": "auto"
    },
    {
        "assessment_criteria": "% of projects with contingency utilization rate > 1",
        "weightage": 0.2,
        "formula": "(Number of projects with contingency utilization > 1) / (Total number of projects)",
        "data_points_used": "CEO-DP-008",
        "calculation_type": "ratio",
        "rating_good": "<10%",
        "rating_satisfactory": "10-30%",
        "rating_needs_improvement": ">30%",
        "pillar": "Cost Estimation & Optimization",
        "description": "Measures the proportion of projects exceeding their contingency budgets",
        "formula_type": "auto"
    },
    {
        "assessment_criteria": "% of projects with Approved Change Requests (design/construction) having a cost impact greater than 2%",
        "weightage": 0.4,
        "formula": "(No. of projects with approved change request having a cost impact greater than 2%) / (Total number of projects)",
        "data_points_used": "CEO-DP-014",
        "calculation_type": "ratio",
        "rating_good": "<5%",
        "rating_satisfactory": "5-15%",
        "rating_needs_improvement": ">15%",
        "pillar": "Cost Estimation & Optimization",
        "description": "Measures the proportion of projects with approved change requests causing cost increases over 2%",
        "formula_type": "auto"
    },
    {
        "assessment_criteria": "% of projects with Approved Claims",
        "weightage": 0.4,
        "formula": "(No. of projects with approved claims) / (Total number of projects)",
        "data_points_used": "CEO-DP-017",
        "calculation_type": "ratio",
        "rating_good": "<2%",
        "rating_satisfactory": "2-5%",
        "rating_needs_improvement": ">5%",
        "pillar": "Cost Estimation & Optimization",
        "description": "Measures the proportion of projects with approved claims",
        "formula_type": "auto"
    },
    {
        "assessment_criteria": "% of provisional sums of the latest PIF Approved Capex budget",
        "weightage": 0.4,
        "formula": "Total Provisional Sums/Latest Approved Budget",
        "data_points_used": "CEO-DP-031,CEO-DP-032",
        "calculation_type": "ratio",
        "rating_good": "<5%",
        "rating_satisfactory": "5-15%",
        "rating_needs_improvement": ">15%",
        "pillar": "Cost Estimation & Optimization",
        "description": "Measures the proportion of provisional sums within the latest approved budget",
        "formula_type": "auto"
    },
    {
        "assessment_criteria": "% of variance of Allocated Provisional sums against the awarded amount",
        "weightage": 0.6,
        "formula": "(Total Provisional Sums - Actual Utilized Provisional Sums)/Total Provisional Sums",
        "data_points_used": "CEO-DP-035",
        "calculation_type": "ratio",
        "rating_good": "<10%",
        "rating_satisfactory": "10-20%",
        "rating_needs_improvement": ">20%",
        "pillar": "Cost Estimation & Optimization",
        "description": "Measures the variance between allocated and utilized provisional sums",
        "formula_type": "auto"
    },
    # -----
    # Innovation & Technology
    # -----
    {
        "assessment_criteria": "Is there an innovation Strategy or document that lists the key focus areas and initiatives across design, construction and operation and aligned with DevCo strategic plan?",
        "weightage": 0.3,
        "formula": "Innovation Strategy: Availability - 15%; Strategic Alignment - 15%; Adequate list of key focus areas - 10%; Adequate list of detailed initiatives - 10%; CBA - 15%; Implementation Roadmap - 15%; Process formulated - 10%; Budget of implementation - 10%",
        "data_points_used": "IT-DP-001,IT-DP-002,IT-DP-003,IT-DP-004,IT-DP-005,IT-DP-006,IT-DP-007,IT-DP-008",
        "calculation_type": "custom",
        "rating_good": ">75%",
        "rating_satisfactory": "60-75%",
        "rating_needs_improvement": "<60%",
        "pillar": "Innovation & Technology",
        "description": "Checks the existence and quality of an innovation strategy aligned with DevCo's strategic plan",
        "formula_type": "auto"
    },
    {
        "assessment_criteria": "Is there a smart city Strategy or document that lists the key  focus areas of smart city aligned with DevCo strategic plan?",
        "weightage": 0.3,
        "formula": "Smart City Strategy: Availability 15%; Strategic Alignment 15%; Adequate key focus areas 10%; Adequate detailed initiatives 10%; Smart city goals nad KPIs 10%; CBA 10%; Implementation Roadmap 10%; Process formulated 10%; Budget of implementation 10%",
        "data_points_used": "IT-DP-010,IT-DP-011,IT-DP-012,IT-DP-013,IT-DP-014,IT-DP-015,IT-DP-016,IT-DP-017,IT-DP-018",
        "calculation_type": "custom",
        "rating_good": ">75%",
        "rating_satisfactory": "60-75%",
        "rating_needs_improvement": "<60%",
        "pillar": "Innovation & Technology",
        "description": "Checks the existence and quality of a smart city strategy aligned with DevCo’s strategic plan",
        "formula_type": "auto"
    },
    {
        "assessment_criteria": "Is there an impact assessment report or identified process/ guidelines to evaluate the impact of the innovation / smart city technologies adoption on DevCo performance?",
        "weightage": 0.1,
        "formula": "Adoption on DevCo performance? Robust assessment process and guidelines - 30%; Availability of sample of impact assessment report - 30%; Availability of action plan - 10%; Use of innovative tools/platforms/dashboards - 30%",
        "data_points_used": "IT-DP-021,IT-DP-022,IT-DP-023,IT-DP-024",
        "calculation_type": "custom",
        "rating_good": ">75%",
        "rating_satisfactory": "60-75%",
        "rating_needs_improvement": "<60%",
        "pillar": "Innovation & Technology",
        "description": "Checks the availability of processes and reports to assess the impact of innovation and smart city technologies on DevCo’s performance",
        "formula_type": "auto"
    },
    {
        "assessment_criteria": "Is there evidence for innovation / smart city technologies successful implementation (in final design report, master plan or other)?",
        "weightage": 0.3,
        "formula": "Effectiveness index in the mentioned areas is an evaluation of successful implementation, (Up to 8.3% for each element of the innovation adoption effective index), (Up to 10% for each element of the smart city adoption effective index)",
        "data_points_used": "IT-DP-025,IT-DP-026,IT-DP-027,IT-DP-028,IT-DP-029,IT-DP-030,IT-DP-031,IT-DP-032,IT-DP-033,IT-DP-034,IT-DP-035",
        "calculation_type": "custom",
        "rating_good": ">75%",
        "rating_satisfactory": "60-75%",
        "rating_needs_improvement": "<60%",
        "pillar": "Innovation & Technology",
        "description": "Checks for documented evidence of successful implementation of innovation and smart city technologies",
        "formula_type": "auto"
    },
    {
        "assessment_criteria": "Are there Pilot or R&D projects conducted?",
        "weightage": 0.5,
        "formula": "Pilot or R&D projects conducted? Availability - 20%; Adequate list of focus areas - 35%; Procedure - 15%; Outcome assessment robustness - 30%",
        "data_points_used": "IT-DP-036,IT-DP-037,IT-DP-038,IT-DP-039",
        "calculation_type": "custom",
        "rating_good": ">75%",
        "rating_satisfactory": "60-75%",
        "rating_needs_improvement": "<60%",
        "pillar": "Innovation & Technology",
        "description": "Assesses the existence and quality of pilot or R&D projects, including focus areas, procedures, and outcomes",
        "formula_type": "auto"
    },
    {
        "assessment_criteria": "% of pilot / R&D Projects Transitioned into Full-Scale",
        "weightage": 0.5,
        "formula": "[(Number of pilots that are scaled successfully + Number of R&D projects that are successfully piloted or fully-scaled) / (Number of pilot projects + Number of R&D projects)]",
        "data_points_used": "IT-DP-040,IT-DP-041,IT-DP-042,IT-DP-043",
        "calculation_type": "ratio",
        "rating_good": ">40%",
        "rating_satisfactory": "20-40%",
        "rating_needs_improvement": "<20%",
        "pillar": "Innovation & Technology",
        "description": "Measures the proportion of pilot and R&D projects successfully transitioned to full-scale implementation",
        "formula_type": "auto"
    },
    {
        "assessment_criteria": "Availability of Innovation unit / department with structured team",
        "weightage": 0.5,
        "formula": "Availability of Innovation: Availability - 20%; Adequate Key positions planned in the org. structure - 30%; Unit/department position within the company hierarchy - 20%; Qualifications of the innovation team - 30%",
        "data_points_used": "IT-DP-044,IT-DP-045,IT-DP-046,IT-DP-047",
        "calculation_type": "custom",
        "rating_good": ">60%",
        "rating_satisfactory": "40-60%",
        "rating_needs_improvement": "<40%",
        "pillar": "Innovation & Technology",
        "description": "Assesses the presence and structure of a dedicated innovation unit within the organization",
        "formula_type": "auto"
    },
    {
        "assessment_criteria": "Availability of Innovation and Technology Strategy / Process & Framework",
        "weightage": 0.5,
        "formula": "Availability - 50%, Implementation of the unit/department framework/ process - 50%",
        "data_points_used": "IT-DP-048,IT-DP-049",
        "calculation_type": "custom",
        "rating_good": ">50%",
        "rating_satisfactory": "50%",
        "rating_needs_improvement": "<50%",
        "pillar": "Innovation & Technology",
        "description": "Assesses the availability and implementation of an innovation and technology strategy or framework",
        "formula_type": "auto"
    },
    # -----
    # Strategy & Operations
    # -----
    {
        "assessment_criteria": "Availability of Technical Function Strategy",
        "weightage": 0.3,
        "formula": "Give 'satisfactory' score if there is a technical function strategy, but it is very general and does not provide specific details of the strategy",
        "data_points_used": "SO-DP-001",
        "calculation_type": "custom",
        "rating_good": "yes",
        "rating_satisfactory": "yes, but very brief",
        "rating_needs_improvement": "no",
        "pillar": "Strategy & Operations",
        "description": "Assesses the availability and quality of a detailed technical function strategy",
        "formula_type": "auto"
    },
    {
        "assessment_criteria": "Alignment of Technical Strategy with Organizational Strategy",
        "weightage": 0.3,
        "formula": "Assess if elements of technical strategy is aligned with organizational strategy. Average score if key elements of organizational strategy is not addressed in technical strategy",
        "data_points_used": "SO-DP-002",
        "calculation_type": "custom",
        "rating_good": "well-aligned",
        "rating_satisfactory": "yes, but very brief",
        "rating_needs_improvement": "no",
        "pillar": "Strategy & Operations",
        "description": "Assesses how well the technical strategy aligns with the overall organizational strategy",
        "formula_type": "auto"
    },
    {
        "assessment_criteria": "Severity of Key Challenges Faced in Strategy Execution Technically",
        "weightage": 0.4,
        "formula": "Severe score if challenges faced can impact strategy execution significantly (in terms of time, cost and/or quality)",
        "data_points_used": "SO-DP-003",
        "calculation_type": "custom",
        "rating_good": "minor",
        "rating_satisfactory": "moderate",
        "rating_needs_improvement": "severe",
        "pillar": "Strategy & Operations",
        "description": "Evaluates the severity of technical challenges that may hinder strategy execution",
        "formula_type": "auto"
    },
    {
        "assessment_criteria": "Availability of Technical KPIs",
        "weightage": 0.4,
        "formula": "Give 'satisfactory' score if there are technical KPIs, but they are very generic",
        "data_points_used": "SO-DP-004",
        "calculation_type": "custom",
        "rating_good": "yes",
        "rating_satisfactory": "yes, but very brief",
        "rating_needs_improvement": "no",
        "pillar": "Strategy & Operations",
        "description": "Assesses the availability and quality of specific technical KPIs",
        "formula_type": "auto"
    },
    {
        "assessment_criteria": "Progress of Achievement of KPIs for Technical Team",
        "weightage": 0.2,
        "formula": "Number of KPIs achieved / Total Number of KPIs set for the same period",
        "data_points_used": "SO-DP-005,SO-DP-006",
        "calculation_type": "ratio",
        "rating_good": ">75%",
        "rating_satisfactory": "50-75%",
        "rating_needs_improvement": "<50%",
        "pillar": "Strategy & Operations",
        "description": "Assesses the availability and quality of specific technical KPIs",
        "formula_type": "auto"
    },
    {
        "assessment_criteria": "Criticality of Vacant/Missing Positions in Organization",
        "weightage": 0.6,
        "formula": "Severe if more than 25% of technical department head (N-2 or 3) and above are vacant. Technical department head: person leading a technical function (depends on organization size). Moderate if 2 position for technical department head are vacant",
        "data_points_used": "SO-DP-008",
        "calculation_type": "custom",
        "rating_good": "minor",
        "rating_satisfactory": "moderate",
        "rating_needs_improvement": "severe",
        "pillar": "Strategy & Operations",
        "description": "Evaluates the impact of vacant or missing technical leadership positions on organizational performance",
        "formula_type": "auto"
    },
    {
        "assessment_criteria": "Appropriateness of Qualifications in Recruitment of Vacant Technical Department Head Positions",
        "weightage": 0.4,
        "formula": "Critical score if there is little to no relevance in the requested qualifications to the role",
        "data_points_used": "SO-DP-018",
        "calculation_type": "custom",
        "rating_good": "well-aligned",
        "rating_satisfactory": "some gaps",
        "rating_needs_improvement": "misaligned",
        "pillar": "Strategy & Operations",
        "description": "Assesses whether qualifications required for vacant technical leadership roles are appropriate and relevant",
        "formula_type": "auto"
    },
    {
        "assessment_criteria": "Robustness of Policy/Guideline/Procedure Communication",
        "weightage": 0.3,
        "formula": "Strong if these are done: 1) Regular update and review of policies (3 mths). 2) All relevant policies/guidelines captured. 3) Easy access (one repository with easy to find link). 4) Multi-channels to inform updates to documents e.g. email, intranet",
        "data_points_used": "SO-DP-019",
        "calculation_type": "custom",
        "rating_good": "strong",
        "rating_satisfactory": "moderate",
        "rating_needs_improvement": "poor",
        "pillar": "Strategy & Operations",
        "description": "Evaluates the effectiveness and thoroughness of communicating policies, guidelines, and procedures",
        "formula_type": "auto"
    },
    {
        "assessment_criteria": "Robustness of Policy/Guideline/Procedure Compliance Monitoring Framework",
        "weightage": 0.4,
        "formula": "Strong if these are done: 1) Regular internal audits of processes (ongoing and rotation of topics/departments). 2) Independent internal audit department reporting directly to CEO or Board. 3) Whistleblowing policy. 4) Regular training for all staff (annual).",
        "data_points_used": "SO-DP-023",
        "calculation_type": "custom",
        "rating_good": "strong",
        "rating_satisfactory": "moderate",
        "rating_needs_improvement": "poor",
        "pillar": "Strategy & Operations",
        "description": "Evaluates the strength of the framework for monitoring compliance with policies, guidelines, and procedures",
        "formula_type": "auto"
    },
    {
        "assessment_criteria": "Robustness of Board Reporting Framework",
        "weightage": 0.3,
        "formula": "Strong if all of these following points are done: 1) Board reporting policy covering frequency/trigger for updates. 2) Register of Board Papers/Presentations. 3) Register of Board meetings and meeting minutes",
        "data_points_used": "SO-DP-025",
        "calculation_type": "custom",
        "rating_good": "strong",
        "rating_satisfactory": "moderate",
        "rating_needs_improvement": "poor",
        "pillar": "Strategy & Operations",
        "description": "Evaluates the effectiveness and structure of the framework for reporting to the Board",
        "formula_type": "auto"
    }
]

with engine.begin() as conn:
    for row in assessment_data:
        conn.execute(
            text("""
                INSERT INTO assessment_matrix (
                    assessment_criteria,
                    weightage,
                    formula,
                    data_points_used,
                    calculation_type,
                    rating_good,
                    rating_satisfactory,
                    rating_needs_improvement,
                    pillar,
                    description,
                    formula_type
                )
                VALUES (
                    :assessment_criteria,
                    :weightage,
                    :formula,
                    :data_points_used,
                    :calculation_type,
                    :rating_good,
                    :rating_satisfactory,
                    :rating_needs_improvement,
                    :pillar,
                    :description,
                    :formula_type
                )

            """),
            row
        )

print("Assessment matrix seeded successfully with pillars.")